var a = 10;
document.write("Result: <br>");
document.write("The value of a is:" + a + "<br><br>");
document.write("..................................................<br><br>");
document.write("The value of ++a is: 11 <br>");
++a;
document.write("Now the value of ++a is:" + a + "<br><br>");
document.write("The value of a++ is: 11<br>");
a++;
document.write("Now the value of a++ is:" + a + "<br><br>");
document.write("The value of --a is: 11 <br>");
--a;
document.write("Now the value of --a is:" + a + "<br><br>");
document.write("The value of a-- is: 11 <br>");
a--;
document.write("Now the value of a-- is:" + a + "<br><br>");
