var a;
document.write("Value after variable declaration is: " + a + "<br>");
a = 5;
document.write("Initial value is: " + a + "<br>");
a++;
document.write("Value after increment is " + a + "<br>");
a = a + 7;
document.write("Value after addition is: " + a + "<br>");
a--;
document.write("Value after decrement is: " + a + "<br>");
var b = a % 3;
document.write("The remainder is: " + b + "<br>");
